//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.aureacode.reportemh;

import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.util.Log;
import android.view.KeyEvent;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.EditText;
import com.aureacode.reportemh.R.id;
import com.aureacode.reportemh.R.layout;
import com.aureacode.reportemh.pojos.Login;
import com.aureacode.reportemh.recursos.Recursos.AnsType;
import com.googlecode.androidannotations.api.BackgroundExecutor;
import com.googlecode.androidannotations.api.SdkVersionHelper;

public final class SignUp_
    extends SignUp
{

    private Handler handler_ = new Handler();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.signup);
    }

    private void init_(Bundle savedInstanceState) {
    }

    private void afterSetContentView_() {
        activityRootView = ((View) findViewById(id.activityRootView));
        edPassSignUp = ((EditText) findViewById(id.ed_pass_sign_up));
        edConfirmpassSignUp = ((EditText) findViewById(id.ed_confirmpass_sign_up));
        edEmailSignUp = ((EditText) findViewById(id.ed_email_sign_up));
        edUserSignUp = ((EditText) findViewById(id.ed_user_sign_up));
        {
            View view = findViewById(id.bt_signup);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        SignUp_.this.sigup();
                    }

                }
                );
            }
        }
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    public static SignUp_.IntentBuilder_ intent(Context context) {
        return new SignUp_.IntentBuilder_(context);
    }

    @Override
    public void doInUiThread(final Login login, final AnsType ansType) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    SignUp_.super.doInUiThread(login, ansType);
                } catch (RuntimeException e) {
                    Log.e("SignUp_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void sigUpBack(final String user, final String email, final String pass) {
        BackgroundExecutor.execute(new Runnable() {


            @Override
            public void run() {
                try {
                    SignUp_.super.sigUpBack(user, email, pass);
                } catch (RuntimeException e) {
                    Log.e("SignUp_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, SignUp_.class);
        }

        public Intent get() {
            return intent_;
        }

        public SignUp_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

    }

}
